### ISSUE TITLE
There should not be a need to "Enable TM.net"

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TeamMentor_Eclipse_Plugin#12]
Right now for TM Guidance to be displayed, every time user starts eclipse, the user needs to click TeamMentor->Enable TeamMentor.net"  This should happen automatically

**Comment by DinisCruz** [comment]
This is an tough one since in Eclipse our plug-in is not invoke until the first time the user does an action to it (i.e. no code is executed until then).

On 1.3.1 I changed this menu option to say 'Open TeamMentor View' which is the same eclipse view that is used to show the TeamMentor Articles (unless the user selected the non-default option to open the articles in a new view)

**Comment by romichg** [comment]
So I need to add this to instructions.  If a user had already clicked on a
finding, will this open up a relevant article? If not - it should.

**Comment by romichg** [comment]
If the user clicked on a finding and then clicked on "Open TeamMentor View", it still brings  up the generic Welcome to The Teammentor Eclips plugin message instead of actual guidance.

**Comment by DinisCruz** [comment]
I think that that is ok, as long as we have a better 'intro' text to go into that page (can you write some?).

I.e. when the user clicks on the 'Open TeamMentor View' it basically opens the landing page for the Eclipse Plug-in.

So what I need is more text to go there

**Comment by romichg** [comment]
Fair enough. I opened two new issues to track this. I am actually now not so sure about the second one.

https://github.com/TeamMentor/Master/issues/654
https://github.com/TeamMentor/Master/issues/655
