### ISSUE TITLE
Show Fortify Guidance when there is no TM guidance

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TeamMentor_Eclipse_Plugin#2]

**Comment by romichg** [comment]
I think this will be confusing. Fortify guidance is already shown on the bottom of the page. Users will come accustomed to seeing TM guidance in the right hand side and will just get confused if they see exactly the same content there as on the bottom pane.  We should display maybe - Sorry no TM guidance exists for this issue - Would you like to help create it?

**Comment by tlaloc75** [comment]
Saying there is no guidance isn't quite right, since there may be guidance that isn't mapped. I think we should always display the best information we have for the vulnerability at hand. If its not TM, then its probably the Fortify guidance. We shouldn't force the user to go back and forth between TM pane and Fortify pane, instead they should be used to always going to the TM pane.

I think we should either:
1) Show the Fortify guidance directly
2) Keep the TM UI/branding, state that there is not a TeamMentor article mapped to this vulnerability and then load the fortify guidance inline.

#2 is probably more understandable but also harder to do.

**Comment by DinisCruz** [comment]
At the moment (1.3.1) we are showing a default 'there is no guidance message' and the question is 'should that prevent the push of 1.3.1'?

**Comment by romichg** [comment]
Actually not sure if this looks good. Can we try showing the Fortify guidance?

**Comment by romichg** [comment]
This is fixed. (tracking issue closed)
